
    
    function myFunction2(inputA) {
    console.log('Входной параметр:', inputA);
    
    
    
    
     let linkBC1 = "";
     let nameBC1 = "";
     
     let linkBC2 = "";
     let nameBC2 = "";
     
     let linkBC3 = "";
     let nameBC3 = "";  
     
     let linkBC4 = "";
     let nameBC4 = ""; 
     
     let linkBC5 = "";
     let nameBC5 = "";
    
    
    
    switch (inputA) {
        
     
case "8200832180":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Абсорбер заднего бампера ( балка бампера пластик )Лада Ларгус 8450000391 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "766313925R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка задняя колесная внутренняя левая в сборе ( универсал ) Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "766319910R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка задняя колесная внутренняя левая в сборе ( фургон ) Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "766306991R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка задняя колесная внутренняя правая в сборе ( универсал ) Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "766304664R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка задняя колесная внутренняя правая в сборе ( фургон ) Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548828":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка задняя колесная правая верхняя ( универсал ) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548829":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Арка панель внутренняя задней боковины правая фургон/универсал (нижняя часть) LADA Largus Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000256":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "БАМПЕРА ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/v-cvet-bamperlargusfl";nameBC4 = "Бампер задний Лада Ларгус/Ларгус FL без паркт. Крашеный 498 Лазурно синий (Темно синий ) Полад";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000257":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Бампер задний (шагрень) Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000245":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "БАМПЕРА ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/v-cvet-bamperlargusfl";nameBC4 = "Бампер передний Лада Ларгус Крашеный 691 Платина (Серебристый) ЗАО Полад";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000244":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Бампер передний (шагрень) Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "ST-DC01-101-0":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Бачок омывателя без мотора Лада Ларгус/Логан /DUSTER/SANDERO";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "760312697R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Боковина левая (Проем передней двери) 8201408130 Лада Ларгус ОРИГИНАЛ";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "760309989R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Боковина правая (Проем передней двери) 8201408131 Лада Ларгус ОРИГИНАЛ";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548849":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Брызговик LADA Largus с лонжероном в сборе левый RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "641006141R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Брызговик LADA Largus с лонжероном в сборе правый Лада Ларгус Румыния";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMTG-DR-10569L":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь багажника левая (глухая) (есть крашенные в цвет) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "901010231R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задка левая (глухая) Лада Ларгус крашенная 691 (Платина)";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMTG-WG-10572L":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь багажника левая (под стекло ) ( есть крашенные в цвет) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548841":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь багажника левая (под стекло ) 6001548841 Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "901004643R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задка правая (глухая) Blue D'azurit Лада Ларгус / LARGUS (FL) NEW Крашенная 498 Лазурно сини";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMTG-DR-10571R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь багажника правая (глухая) (есть крашенные в цвет) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMTG-WG-10573R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь багажника правая (под стекло) (есть крашенные в цвет) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "901005637R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задка правая (под стекло) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821010763R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя левая (глухая) (без молдинга) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821015688R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя левая (глухая) (с отв. под молдинг) Лада Ларгус крашенная 242 (Серый Базальт Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821017307R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя левая (под стекло) (под молдинг) Лада Ларгус крашенная 242 (Серый Базальт) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821013317R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя левая (под стекло) (без молдинга) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821008665R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя правая (глухая) (под молдинг) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821006680R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь задняя правая (глухая) (под молдинг под личинку ) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821009310R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя правая ( под стекло ) (под молдинг) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "821008009R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь задняя правая (под стекло) под молдинг) Лада Ларгус крашенная 242 (Серый Базальт) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMDF-13295L":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя левая (без молдинга) Лада Ларгус / Logan (04 13 )";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "801012741R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь передняя левая Лада Ларгус крашенная 283 (Кашемир) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMDF-0790L":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя левая (под молдинг) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "801013696R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь передняя левая (с отв. под молдинг) Лада Ларгус крашенная 691 (Платина)";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "GMDF-13296R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя правая (без молдинга) Логан/Лада Ларгус (04 13 )";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "801004751R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "КАТАЛОГ LADA LARGUS / LARGUS FL КРАШЕННЫЕ ДЕТАЛИ В ЦВЕТ";linkBC2 = "/ladalargus/largusfldetalivcvet";nameBC3 = "ДВЕРИ ЛАРГУС / LARGUS FL В ЦВЕТ";linkBC3 = "/dveriladalrgus-v-cvet";nameBC4 = "Дверь передняя правая (без молдинга) Лада Ларгус крашенная 691 (Платина) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;

//до этого момента все работает


case "GMDF-0789R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя правая (под молдинг под личинку) Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "801002133R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя правая (под молдинг) Лада Ларгус крашенная 242 (Серый Базальт) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450106998":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дверь передняя правая ( под молдинг без личинки ) c 28.05.2019 LADA Largus Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "7700838358":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Дефлектор вытяжной вентиляции багажника 7700419636 Лада Ларгус / LADA Vesta Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200825457":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Жабо решетка воздухозаборника ветрового окна левая Лада Ларгус Румыния";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001546859":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Жабо решетка воздухозаборника ветрового окна правая Лада Ларгус Румыния";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "99999901004103":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Жабо цельное накладка в проем стеклоочистителей LADA Largus (ABS Доп-оборудование )";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000251":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Заглушка бампера ПТФ ЛЕВАЯ Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000250":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Заглушка бампера ПТФ ПРАВАЯ Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000254":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Заглушка бампера окна под буксир крюк шершавый Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "825032094R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний задний левый с эл. приводом 2 контактов Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "825028375R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний задний правый с эл. приводом 2 контактов Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "825021157R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний задний правый с эл. приводом фургон Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "805037344R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний левый механический Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "805037813R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний левый с эл. приводом 2 контактов Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "805036313R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний левый с эл. приводом 5 контактов Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "805024413R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний правый механический сборе Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "805024577R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний правый с эл. приводом 2 контактов Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200928491":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери внутренний передний правый с эл. приводом Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001550300":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок двери задка Лада Ларгус Оригинал RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001547332":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок капота LADA Largus/Лада Ларгус RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "NP511-07621":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Замок капота Лада Ларгус";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "R90.8201021-20":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое левое механическое с накладкой LADA Largus/ Сандеро / Дастер г. Димитровград";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "R90.8201021-21":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое левое с накладкой (с эл, приводом и электрообогрево LADA Largus / г. Димитровград";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "963023520R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое левое элект.обогрев. (без наружн. облиц) Ларгус / Сандеро / Дастер RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "AFK772126":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое правое механическое Ларгус / Логан Сандеро / Дастер ANYU";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "R90.8201020-20":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое правое механическое с накладкой LADA Largus/ Сандеро / Дастер г. Димитровград";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "R90.8201020-21":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое правое с накладкой (с эл, приводом и электрообогревом ) LADA Largus / Димитровград";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "963017247R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало боковое правое элект.обогрев. (без наружн. облиц) Ларгус / Сандеро / Дастер RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "7700413867":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркало салонное заднего вида LADA Largus / LADA Vesta / XRAY LADA Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "ST1210013":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркальный элемент левый с обогревом Ларгус / Логан Сандеро / Дастер";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "ST1210014":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Зеркальный элемент правый с обогревом Ларгус / Логан Сандеро / Дастер";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200751779":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Катафот заднего бампера лев. Лада Ларгус /Логан (2010)";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200751778":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Катафот заднего бампера прав. Лада Ларгус /Логан (2010)";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200846225":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Кронштейн заднего бампера левый (с клипсами ) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200846262":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Кронштейн заднего бампера правый (с клипсами ) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548824":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Кронштейн крепления заднего бампера Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "762951330R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Кронштейн крыла передний левый (сое ль панели брызг) Лада Ларгус (FL) NEW АвтоВАЗ";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "676004737R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Кронштейн крыла передний правый (сое ль панели брызг) Лада Ларгус (FL) NEW АвтоВАЗ";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450104265":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Крыло заднее левое (глухое) Лада Ларгус (катафорез) RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450104266":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Крыло заднее левое (с окном) Лада Ларгус (катафорез) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450104264":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Крыло заднее правое (глухое ) Лада Ларгус (катафорез) RENAULT";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450104267":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Крыло заднее правое (с окном) Лада Ларгус (катафорез) Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "36048403011":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Крыло переднее левое Лада Ларгус/Логан Начало";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8201034220":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерон задний левый Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8201034230":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерон задний правый в сборе Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "751118394R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерон передний левый (пер. внутрен. часть) 6001546949 Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "751103319R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерон передний правый . (пер. внутрен. часть) Лада Ларгус 751102806 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "751336085R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерона пер. лев. накладка наружняя (усилитель) Лада Ларгус 6001546944 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "751321765R":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лонжерона пер. прав. накладка наружняя (усилитель) Лада Ларгус 6001551799 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450109478":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Лючок бензобака Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000595":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг арки колеса зад. левый Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000596":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг арки колеса зад.правый Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200419798":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг арки колеса передний левый Лада Ларгус 6001548285 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001548286":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг арки колеса передний правый Лада Ларгус 6001548286 Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001549297":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг двери задней левой ( с пистонами ) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001549296":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг двери задней правой ( с пистонами) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001549298":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг двери передней левой ( с пистонами) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "6001549299":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг двери передней правой ( с пистонами) Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000246":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг решетки радиатора хром Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8450000247":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Молдинг решетки радиатора черный Лада Ларгус ЗАО Полад Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;
case "8200553159":nameBC1 = "Каталог";linkBC1 = "/katalog-avtozapchastey";nameBC2 = "Lada Largus";linkBC2 = "/katalog-avtazapchasti-ladalargus";nameBC3 = "КУЗОВНЫЕ ДЕТАЛИ ДЛЯ LADA LARGUS";linkBC3 = "/kyzovnie-detali-lada-largus";nameBC4 = "Накладка двери задка левая (универсальная ) 6001549301 Лада Ларгус Оригинал";linkBC4 = "";nameBC5 = "";linkBC5 = "";break;

//тут тоже еще работает

default: linkBC1 = ""; nameBC1 = ""; linkBC2 = ""; nameBC2 = ""; linkBC3 = ""; nameBC3 = "";  linkBC4 = ""; nameBC4 = ""; linkBC5 = ""; nameBC5 = ""; break;
	}     
	
	var myArray = [];
	
	if (linkBC1 !== "")
	{
	    myArray[0] = nameBC1;
	    myArray[1] = linkBC1;
	    myArray[2] = nameBC2;
	    myArray[3] = linkBC2;
	    myArray[4] = nameBC3;
	    myArray[5] = linkBC3;
	    myArray[6] = nameBC4;
	    myArray[7] = linkBC4;
	    myArray[8] = nameBC5;
	    myArray[9] = linkBC5;
        console.log("NE PUSTOE1");  
	};
	
	console.log(myArray);
	 return myArray;
	
};
